name: build ghc cross compiler

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      release_tag:
        description: Tag to be used for github release ( of format 'v[0-9]+.[0-9]+.[0-9]+' )
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"
    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - name: Build
        run: |
          mkdir ./out-dir
          touch ./out-dir/placeholder.zip
          # Process tag '%ci:no-build' that may be added as line to commit message.
          # Forces CI to cancel current build with status 'passed'.
          if grep -qiP '^\s*%ci:no-build\s*$' <(git log --format="%B" -n 1 "HEAD"); then
            echo "[!] Force exiting as tag '%ci:no-build' was applied to HEAD commit message."
            exit 0
          fi
          rm ./out-dir/placeholder.zip

          ./run-docker.sh ./build-ghc-cross-compiler.sh ./out-dir ${{ matrix.target_arch }}

      - name: Store files
        uses: actions/upload-artifact@v2
        with:
          name: ghc-${{ matrix.target_arch }}
          path: ./scripts/out-dir/*.tar.xz

  create-release:
    needs: build
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      # Must perform checkout first, since it deletes the target directory
      # before running, and would therefore delete the downloaded artifacts
      - uses: actions/checkout@v2

      - name: Get files
        uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ];then
            RELEASE_TAG="${{ github.event.inputs.release_tag }}"
          else
            RELEASE_TAG="${GITHUB_REF#refs/*/}"
          fi

          if gh release view "${RELEASE_TAG}"; then
            # If release exists then update it.
            echo "Updating release with '${RELEASE_TAG}'."
            gh release upload "${RELEASE_TAG}" ./ghc-*/*.tar.xz --clobber
          else
            echo "Creating release with '${RELEASE_TAG}'."
            gh release create "${RELEASE_TAG}" ./ghc-*/*.tar.xz
          fi
